### ISSUE TITLE
f-strings not recognized

### ISSUE THREAD

**Issue by mobiusKey** [Sevaarcen/RADAR#31]
after running pip install -r requirements.txt the f-strings are throwing an invalid syntax error when trying to run server.py

![Selection_002](https://user-images.githubusercontent.com/44487277/81034474-49d8af80-8e65-11ea-8345-60a4098c1208.png)

Running on Ubuntu 16.04 32 bit python 2.7.12

**Comment by Sevaarcen** [comment]
Hello,

F-strings are a new method for formatting strings in python that was introduced in version 3.6. The error you get is what happens when you run RADAR on a version that isn't supported (<3.6). Please rerun the python file using a python version of 3.6 or higher.

**Comment by mobiusKey** [comment]
thanks for the help. I think it would be useful to change line 17 to #!/usr/bin/python3 so that its known you want to use python3 and not python2. This way if you also just execute the file the system knows which python version to run

**Comment by Sevaarcen** [comment]
Yeah that's a good idea, I added the shebang line to the 4 executable python files in the latest commit.
